In [7]:
import pandas as pd

cpi = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/cpi.csv")
avocado = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/avocado_price.csv")
tomato = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/tomato_price.csv")

avocado.head()

  REF_DATE                        GEO  VALUE
0  2017-01                     Canada   1.51
1  2017-01  Newfoundland and Labrador   2.06
2  2017-01       Prince Edward Island   1.40
3  2017-01                Nova Scotia   1.35
4  2017-01              New Brunswick   1.42

In [11]:
cpi = cpi[cpi["Product"] != "Gasoline"]

cpi = cpi.set_index("Product").T.reset_index()

cpi.columns = ["Date", "Food"]

cpi["Date"] = cpi["Date"].astype(str)
cpi["Date"] = cpi["Date"].str[:4] + "-" + cpi["Date"].str[4:]

cpi.head()

      Date   Food
0  2016-01  144.6
1  2016-02  145.0
2  2016-03  144.5
3  2016-04  143.8
4  2016-05  143.3

In [ ]:
avocado = avocado[avocado["GEO"] == "Canada"].reset_index(drop=True)
tomato = tomato[tomato["GEO"] == "Canada"].reset_index(drop=True)

In [14]:
merged_avo = pd.merge(
    avocado,
    cpi,
    left_on="REF_DATE",
    right_on="Date",
    how="inner"
)

merged_avo = merged_avo.drop(columns=["GEO", "Date"])

merged_avo = merged_avo.rename(columns={
    "REF_DATE": "date",
    "VALUE": "price_before_adjustment",
    "Food": "cpi"
})

base_cpi = merged_avo.loc[merged_avo["date"] == "2017-01", "cpi"].iloc[0]

merged_avo["price_adjusted"] = (
    merged_avo["price_before_adjustment"] * base_cpi / merged_avo["cpi"]
)

merged_avo["price_adjusted"] = merged_avo["price_adjusted"].round(2)

merged_avo.to_csv("/Users/jli624/Desktop/cmpt733/project/avocado_price_adjusted.csv", index=False)

In [15]:
merged_tom = pd.merge(
    tomato,
    cpi,
    left_on="REF_DATE",
    right_on="Date",
    how="inner"
)

merged_tom = merged_tom.drop(columns=["GEO", "Date"])

merged_tom = merged_tom.rename(columns={
    "REF_DATE": "date",
    "VALUE": "price_before_adjustment",
    "Food": "cpi"
})

base_cpi = merged_tom.loc[merged_tom["date"] == "2017-01", "cpi"].iloc[0]

merged_tom["price_adjusted"] = (
    merged_tom["price_before_adjustment"] * base_cpi / merged_tom["cpi"]
)

merged_tom["price_adjusted"] = merged_tom["price_adjusted"].round(2)

merged_tom.to_csv(
    "/Users/jli624/Desktop/cmpt733/project/tomato_price_adjusted.csv",
    index=False
)