In [2]:
import pandas as pd

imported = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/avocado_imported_from_mexico.csv")

imported.head()

,refYear,refMonth,qty,altQty,netWgt,fobvalue,primaryValue
0,2016,1,7371524.0,7371524,7371524.0,1.267176e+07,1.267176e+07
1,2016,2,6118500.0,6118500,6118500.0,1.084844e+07,1.084844e+07
2,2016,3,6829811.0,6829811,6829811.0,1.232077e+07,1.232077e+07
3,2016,4,7678612.0,7678612,7678612.0,1.383802e+07,1.383802e+07
4,2016,5,6615593.0,6615593,6615593.0,1.489952e+07,1.489952e+07

In [3]:
# create date column in yyyy-mm format
imported["date"] = (
    imported["refYear"].astype(str) + "-" +
    imported["refMonth"].astype(str).str.zfill(2)
)

# keep only date and qty
imported_clean = imported[["date", "qty"]]

# convert qty to integer
imported_clean["qty"] = imported_clean["qty"].astype(int)

# export CSV
imported_clean.to_csv(
    "/Users/jli624/Desktop/cmpt733/project/avocado_import.csv",
    index=False
)

/var/folders/7j/4d_gnbqx14s1px8z4_03t8p40000gn/T/ipykernel_19364/1121334909.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  imported_clean["qty"] = imported_clean["qty"].astype(int)

In [4]:
tomato = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/tomato_import_mexico_us.csv")
tomato.head()

,refYear,refMonth,partnerDesc,qty,altQty,netWgt,fobvalue,primaryValue
0,2016,1,Mexico,21843750.0,21843750,21843750.0,4.749718e+07,4.749718e+07
1,2016,1,USA,3901699.0,3901699,3901699.0,9.320120e+06,9.320120e+06
2,2016,2,Mexico,22881859.0,22881859,22881859.0,3.752664e+07,3.752664e+07
3,2016,2,USA,3222170.0,3222170,3222170.0,6.306887e+06,6.306887e+06
4,2016,3,Mexico,20563433.0,20563433,20563433.0,3.342466e+07,3.342466e+07

In [5]:
# create date column yyyy-mm
tomato["date"] = (
    tomato["refYear"].astype(str) + "-" +
    tomato["refMonth"].astype(str).str.zfill(2)
)

# keep relevant columns
tomato_clean = tomato[["date", "partnerDesc", "qty"]]

# rename column
tomato_clean = tomato_clean.rename(columns={"partnerDesc": "partner"})

# convert qty to integer
tomato_clean["qty"] = tomato_clean["qty"].astype(int)

# export CSV
tomato_clean.to_csv(
    "/Users/jli624/Desktop/cmpt733/project/tomato_import.csv",
    index=False
)