In [1]:
import pandas as pd

avo_cpi = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/avocado_cpi.csv")
tom_cpi = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/tomatoes_cpi.csv")
avocado = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/avocado_price.csv")
tomato = pd.read_csv("/Users/jli624/Desktop/cmpt733/project/tomato_price.csv")

In [4]:
avo_cpi = avo_cpi.rename(columns={"refPer": "date"})
avo_cpi["date"] = avo_cpi["date"].str[:7]
avo_cpi.head()

      date  value
0  2016-01  146.2
1  2016-02  147.9
2  2016-03  136.8
3  2016-04  131.2
4  2016-05  131.0

In [5]:
tom_cpi = tom_cpi.rename(columns={"refPer": "date"})
tom_cpi["date"] = tom_cpi["date"].str[:7]
tom_cpi.head()

      date  value
0  2016-01  174.8
1  2016-02  169.2
2  2016-03  141.2
3  2016-04  122.1
4  2016-05   96.8

In [6]:
avocado = avocado[avocado["GEO"] == "Canada"].reset_index(drop=True)
tomato = tomato[tomato["GEO"] == "Canada"].reset_index(drop=True)

In [7]:
avocado.head()

  REF_DATE     GEO  VALUE
0  2017-01  Canada   1.51
1  2017-02  Canada   1.52
2  2017-03  Canada   1.66
3  2017-04  Canada   1.92
4  2017-05  Canada   2.14

In [10]:
merged_avo = pd.merge(
    avocado,
    avo_cpi,
    left_on="REF_DATE",
    right_on="date",
    how="inner"
)

merged_avo = merged_avo.drop(columns=["GEO", "date"])

merged_avo = merged_avo.rename(columns={
    "REF_DATE": "date",
    "VALUE": "price_before_adjustment",
    "value": "cpi"
})

base_cpi = merged_avo.loc[merged_avo["date"] == "2017-01", "cpi"].iloc[0]

merged_avo["price_adjusted"] = (
    merged_avo["price_before_adjustment"] * base_cpi / merged_avo["cpi"]
)

merged_avo["price_adjusted"] = merged_avo["price_adjusted"].round(2)

merged_avo.to_csv("/Users/jli624/Desktop/cmpt733/project/avocado_price_adjusted.csv", index=False)

In [11]:
merged_tom = pd.merge(
    tomato,
    tom_cpi,
    left_on="REF_DATE",
    right_on="date",
    how="inner"
)

merged_tom = merged_tom.drop(columns=["GEO", "date"])

merged_tom = merged_tom.rename(columns={
    "REF_DATE": "date",
    "VALUE": "price_before_adjustment",
    "value": "cpi"
})

base_cpi = merged_tom.loc[merged_tom["date"] == "2017-01", "cpi"].iloc[0]

merged_tom["price_adjusted"] = (
    merged_tom["price_before_adjustment"] * base_cpi / merged_tom["cpi"]
)

merged_tom["price_adjusted"] = merged_tom["price_adjusted"].round(2)

merged_tom.to_csv(
    "/Users/jli624/Desktop/cmpt733/project/tomato_price_adjusted.csv",
    index=False
)